[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#26c6da"
backgroundColor = "#07071a"
secondaryBackgroundColor = "#0f0f26"
textColor = "#e0e0f0"
